### ISSUE TITLE
Unable to login locally once SSO created account

### ISSUE THREAD

**Issue by michaelepayne** [psignoret/aad-sso-wordpress#35]
When a new user authenticates via SSO (office 365) the plugin creates the users account in wordpress and authenticates them for access.  If the user logs out of office 365 and attempts to login, this time using the wordpress login form and enters their office 365 email/password they are not authenticated to the wordpress site. 

This came about when trying to setup a blogging software (MS Word and LIve Writer) to authenticate to the blog.

**Comment by psignoret** [comment]
It sounds like you were expecting the user to be able to use their Azure AD (Office 365) username and password in the WordPress form--this won't work, for starters, because WordPress would have no way of verifying the password.

When a WordPress user is auto-provisioned, they *must* use  Azure Active Directory (AD) to sign in (e.g. clicking on the "Sign in with a ___ account"). If you have a scenario where the auto-provisioned user needs to us "local" (to WordPress) account to sign in, a WordPress admin can reset the auto-provisioned user's password. (However, this may or may not be the same as the Office 365 password, and it sort of defeats the whole purpose of this plugin.)

(It is technically feasible to pass Azure AD the username and password under the hood, but this approach only works in certain scenarios. For example, if the user's password has expired, the only place to do the required password change is in the Azure AD sign-in flow. It's a more secure approach to hand the entire authentication flow over to Azure AD.)

**Comment by michaelepayne** [comment]
Thanks.  That was the answer I was expecting.  Is it possible then to remove the local login option and simply redirect every user to the Azure AD sign it since that is how we want all users to sign on anyways.  
It would be nice if there was a way (via a specific URL) to bypass the SSO and allow a "backdoor" login for a non Azure AD admin to gain access should something break.

thanks.

**Comment by psignoret** [comment]
You can use the [`enable_auto_forward_to_aad`](https://github.com/psignoret/aad-sso-wordpress/blob/1cbc1de5d89b1e987aeb346e907a709358b4c1d3/Settings.php#L74) config option in the `Settings.json` file:

    "enable_auto_forward_to_aad": true,

The current implementation doesn't have a magic word that can be used to save yourself from being locked out, but it does introduce a filter named `aad_auto_forward_login` which allows you to set one up yourself to override the config value. For example, if you add this to your theme's `functions.php` file:

    add_filter('aad_auto_forward_login', 'save_me_from_lockout');
    function save_me_from_lockout($should_redirect) {
        if ($_GET['oops'] == '1') {
            return false;
        }
        return $bypass;
    }

You can override the auto-redirect by passing in `oops=1` as a query parameter when going to WP-Admin:

    https://www.example.com/wp-admin?oops=1

**Comment by michaelepayne** [comment]
Perfect.  That will work for me.  

Thanks

**Comment by michaelepayne** [comment]
I entered that code but I'm still getting the login screen.  Is there a particular order to the entries that has to be followed.
Here is the settings.json file.
{
	"org_display_name": "Cadence International",
	
	"client_id":        "8aaadd83-09db-468b-aabb-90c052369b9d",
	"client_secret":    "XWT5viIpEMkRJpZJFmdfvKo4wOE7+zBPeHeNK385m6Y=",

	"field_to_match_to_upn": "email",
	"enable_auto_provisioning": true,
	"enable_auto_forward_to_aad": true,
	"default_wp_role": "subscriber"
}

**Comment by psignoret** [comment]
(Careful, don't post your settings file in it's entirety--the `client_secret` is a secret. You should remove your existing key and create a new one, just to be safe.)

Order should not matter. I'll give it a whirl (it has been some time since I used this config value myself) and get back to you soon.

**Comment by psignoret** [comment]
OK, I tested this out and it's working as expected (well, I had a typo in the "oops" filter above, which I've corrected now). My `Settings.json` includes `"enable_auto_forward_to_aad": true`.

If I go to `http://www.example.com/wp-admin`, I'm immediately redirected to Azure AD to sign in. If I go instead to `http://www.example.com/wp-login.php?oops=1`, I am presented with the regular login form.

Can you confirm that when you go to `<your blog>/wp-admin` you are *not* redirected to Azure AD automatically?

**Comment by michaelepayne** [comment]
It is still not working for me.  I still get the login prompt.

**Comment by psignoret** [comment]
What version of the plugin do you have? (You can see this in the Pugins page.)

**Comment by michaelepayne** [comment]
0.4a

**Comment by psignoret** [comment]
And how long ago did you install the plugin?

**Comment by michaelepayne** [comment]
2 weeks at most

**Comment by psignoret** [comment]
Strange, it would seem this is specific to your blog/installation. Do you get any error messages? When you visit `.../wp-admin`, what does the URL you are redirected to look like?

Here are some things you can try:

1. Use a fresh browser session (e.g. Chrome's Incognito, or IE's InPrivate).
2. Temporarily disable all other plugins. Perhaps this is introduced by conflict of plugins.
3. Triple-check that you have updated the `Settings.json` file on the server, and not a local copy, or the sample `Settings.template.json`.

**Comment by michaelepayne** [comment]
http://intranet.cdncdev.com/wp-login.php?redirect_to=http%3A%2F%2Fintranet.cdncdev.com%2Fwp-admin%2F&reauth=1

1.  Tried both incognito and ie same result
3.  See image.
![image](https://cloud.githubusercontent.com/assets/16187113/11647289/ab24ec7e-9da9-11e5-8a21-b00c415f214d.png)
2.  I'll try them one at a time./

**Comment by michaelepayne** [comment]
disabled the plugins and still no go

**Comment by michaelepayne** [comment]
Changed the order of the commands to
        "field_to_match_to_upn": "email",
	"enable_auto_provisioning": true,
	"default_wp_role": "subscriber",
	"enable_auto_forward_to_aad": true

and it works now.

**Comment by michaelepayne** [comment]
what was the fixed command in the oops?

**Comment by psignoret** [comment]
Very strange. Order shouldn't matter. I'll take a look at this to figure out why.
Thanks for reporting!





On Mon, Dec 7, 2015 at 7:59 PM -0800, "michaelepayne" <notifications@github.com> wrote:





Changed the order of the commands to
        "field_to_match_to_upn": "email",
        "enable_auto_provisioning": true,
        "default_wp_role": "subscriber",
        "enable_auto_forward_to_aad": true

and it works now.

---

**Comment by michaelepayne** [comment]
Appreciate all your help.  This is now working perfectly for me.

**Comment by andre4s** [comment]
Used this on a site and found that using `key` as the query string failed: it redirected as usual. Having done some digging, I guess it's probably because [`key` is used for password reset](https://github.com/WordPress/WordPress/blob/71fb840a24b6b9cffe9d6a16a283b875d7247d02/wp-login.php#L368). Both `auth` and `secret` worked, but the important thing I guess is not to use any parameters already used by WP.

**Comment by psignoret** [comment]
@andre4s I'm a bit confused here. What query string are you referring to?

**Comment by andre4s** [comment]
@psignoret I'm referring to [your code above](https://github.com/psignoret/aad-sso-wordpress/issues/35#issuecomment-162736279) that disables auto-forward when a certain query string is appended to the login URL. I didn't want to use `oops` and discovered by accident that `key` doesn't work as an alternative.

**Comment by psignoret** [comment]
Ah! That's a great point! I updated [the example](https://github.com/psignoret/aad-sso-wordpress/issues/35#issuecomment-162736279) to use a collision-resistant value (like @bradkovach mentions). I also added #117 to track adding a built-in mechanism, to avoid having to set a filter.

**Comment by andre4s** [comment]
Have now encountered another issue: when using the fallback URL, the login form still posts to `/wp-login.php` (without the query string) and redirects to Azure anyway. Have experimented with manually changing POST URL to include string and it works as expected.

**Comment by psignoret** [comment]
Interesting, in a past test of mine, the WordPress native login would kick in be for and prevent the redirect. Good find! I'll look into this and address it in the next couple days.

**Comment by Bsalarius** [comment]
It seems like one method for preventing WordPress POSTing from the login form and causing the redirect is to add a snippet (or modify the snippet from above):

```php
function aad_login_avoid_post($should_redirect) {
    if (!empty($_POST)) {
        return false;
    } else {
        return $should_redirect;
    }
}
add_filter('aad_auto_forward_login', 'aad_login_avoid_post');
```

Hopefully this will help someone!
